### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method encrypt on channel flutter_aes)

### ISSUE THREAD

**Issue by chao9267** [jlcool/flutter_aes#2]
String asekey='K6fqU0CxJlPiZrO0KD0H4hDYxbgrWJ2k';
String _iv = "0000000000000000";
String strA='abc';
    var encryptData = base64.encode(await FlutterAes.encrypt(utf8.encode(strA), utf8.encode(asekey), utf8.encode(_iv)));

  the code throw error:
Unhandled Exception: MissingPluginException(No implementation found for method encrypt on channel flutter_aes)

v1.9.1+hotfix.6

**Comment by jlcool** [comment]
是不是 没有 flutter packages get
